---
title: "Topics for Stat 101"
output: 
  html_document:
    rmdformats::material
  pdf_document: tint::tintPdf
---

# Overview

*Stat 101* is one name for the conventional introductory statistics course. This site contains lessons for teaching topics generally found in Stat 101, but rooting them in real data. 

The topics currently in the collection are

#. data and variables *not yet*
#. center and spread
#. proportions *not yet*
#. the t-test
#. the normal distribution
#. linear regression

```{r include = FALSE}
library(littleapp2)
lesson_format_string <- function(base_name) {
  glue::glue("Formats: [web](Lessons/{base_name}.html) : [pdf](Lessons/{base_name}.pdf) : [word](Lessons/{base_name}.docx) : [Rmd](Lessons/{base_name}.Rmd) : [edit](https://github.com/StatPREP/Hub_leader_lessons/edit/master/Lessons/{base_name}.Rmd)")
}
```

These *Topics for Stat 101* generally involve computing. We provide the resources for this in  the form of mouse-driven, web-based "Little Apps". Using these Little Apps requires an ordinary web browser and nothing more.

Each of the topics contains a number of components:

1. Instructor facing
    - A brief orientation to the statistical method.
    - A description of how the method fits in with statistical practice.
    - The conceptual pitfalls faced by students and instructors and common misconceptions frequently encounted among statistics instructors.
    - A detailed statement of learning objectives written with an eye to assessment of whether those objectives have been met.
    - The background needed by students to undertake each lesson.
    - Tips on using the lesson to create an active classroom. (There's also a set of [general tips to foster student engagement and activity](General/tips-for-active-classroom.Rmd))
    - Items that can be used for assessment. (NA)
    - A "pushing the envelope" section to help instructors who want deeper insight into the statistical methods, including a description in which the traditional topics have become obsolete or no longer reflect good statistical practice.
    

2. Student facing
    - Individual lesson documents illuminating varied aspects of or approaches to the topic. Many of these are best used as in-class, small-group activities, but they can also be used  the basis for class lectures. The documents can be customized, extended, or simplified by the instructor.
    - The Little Apps around which most of the lessons have been written, but which are flexible enough to support free exploration of statistical topics either led by the instructor or self-guided by the student.


The Little Apps can be used with or without the lessons. The Apps are designed to use data to present broad statistical concepts, including descriptive statistics, modeling, statistical inference, and hypothesis tests. The interactive format allows students to explore many data sets and many variables within each data set. The data have been selected from published sources and provide many real settings for informative statistical investigation. The Apps allow students to work with multiple variables and generally provide facilities for working with covariates. 


# Data and variables 

[Instructor guide](???) Not yet available

Applicable lessons:

#. Point plots. `r lesson_format_string("point-plot")`
#. Variable types. `r lesson_format_string("variable-types")`
#. Variables and the unit of observation `r lesson_format_string("variables-and-units")`
#. Response and explanatory variables`r lesson_format_string("response-and-explanatory")`


# Center and spread

[Instructor guide](center-spread/instructions-center-spread.Rmd)

Applicable lessons:

#. Link to Joe Roith's lesson
#. Summary intervals. `r lesson_format_string("summary-interval")`
#. Shapes of distributions. `r lesson_format_string("distribution-shapes")`
#. Standard deviation and the summary interval. `r lesson_format_string("sd_and_summary_interval")`




# Proportions 

[Instructor guide]() *not yet*

Applicable lessons:

#. Not yet available

Note, will be based on proportions app.

# t-test

[Instructor guide](two-sample-t-test/instructions-two-sample-t-test.Rmd)

Applicable lessons:

#. Comparing two groups. `r lesson_format_string("comparing-two-groups")`
#. Comparing confidence intervals. `r lesson_format_string("comparing-confidence-intervals")`
#. Two-sample t-test. `r lesson_format_string("two-sample-t-test")`

# Normal distribution

[Instructor guide](normal-distribution/instructions-normal-distribution.Rmd)

Applicable lessons:


#. Normal parameters. `r lesson_format_string("normal-parameters")`
#. Common and rare. `r lesson_format_string("common-and-rare")`
#. Distribution shapes. `r lesson_format_string("distribution-shapes")`

# Linear regression

[Instructor guide](linear-regression/instructions-linear-regression.Rmd)

Applicable lessons:

#. Describing linear relationships. `r lesson_format_string("relationship-patterns")`
#. How much variation is accounted for? `r lesson_format_string("how-much-is-explained")`

# Modeling 

[Instructor guide]() not yet available

#. Response and explanatory variables. `r lesson_format_string("response-and-explanatory")`
#. How much variation is accounted for. `r lesson_format_string("how-much-is-explained")`




















## Who's who

- Helen Burn
- Carol Howald
- Joe Roith
- Thomas Kinzeler
- Danny Kaplan is the series editor and the author of the Little Apps.